version: '3'
services:

  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn tripfriend.wsgi:application --bind 0.0.0.0:8000 --timeout=300
    environment:
      DJANGO_SETTINGS_MODULE: tripfriend.settings.prod
    env_file:
      - .env
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8000
    entrypoint:
      - sh
      - config/docker/entrypoint.prod.sh

  nginx:
    container_name: nginx
    build: ./config/nginx
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    ports:
      - "80:80"
    depends_on:
      - web

  redis-server:
    container_name: redis-server
    image: redis:5.0-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redis:/home/app/web/data

  worker:
    container_name: worker
    build:
      context: ./
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    command: celery multi start -A tripfriend worker1 worker2 worker3 --loglevel=info
    environment:
      DJANGO_SETTINGS_MODULE: tripfriend.settings.prod
    env_file:
      - .env
    entrypoint:
      - sh
      - config/docker/entrypoint.prod.sh
    depends_on:
      - redis-server

volumes:
  static:
  media:
  redis: